### PR TITLE
Create RUThumbKeyWriter.kt

### PR DESCRIPTION
**Pull request by Defrobe**
RU Writer layout based on RUThumbKeySymbols. Added russian typographic quotation marks, typographic en and em dashes, and ellipsis punctuation mark.

### CODE REVIEW

**Review by dessalines — CHANGES_REQUESTED** [review]
Check the other PRs for adding keyboards, you also need to add this to KeyboardLayout.kt.

**Comment by Defrobe** [comment]
Sorry, I'm working with GitHub for the first time. I've modifyied KeyboardLayout.kt in the fork. What should I do next?

**Comment by dessalines** [comment]
You would do that in this fork, but don't worry about it, I'll get it.

**Review by dessalines — APPROVED** [review]

**Comment by Defrobe** [comment]
Thank you. Hope next time I'll do everything correctly.

**Pull request merged**
