### PR TITLE
New features

### LINKED ISSUE #343: More SwipeNWay types
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

** Describe the feature request below **
Please add these swipe types in `Utils.kt`, i intend to use them in the keyboard i made later.
image
i'll most likely add them myself in a bit though, just don't have Android Studio set up for testing currently.

### LINKED ISSUE #344: Swipe Assist for unused EIGHT_WAY swipes
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

** Describe the feature request below **
Take for example a key like this:
image
If you swipe right, but not pefrectly diagonally up or down, it just sends t. What i'm proposing is a sort of "aim-assist" for swiping (only for EIGHT_WAY swipes for now, since others handle the swiping way more gracefully)
- When making a swipe that would fall into an undefined spot, check the distance to it's nearest neighbours.
- If the distance from the nearest neigbour is < 45deg, send the nearest neighbour
    - 360 / 8 = 45, if we swipe left on the example key, the nearest neighbour might be ť, but we don't want that since it's too far away. in that case just send the base letter.
- optionally, make this a configurable setting, since someone might not like it, e.g. "More Flexible Swiping"
- this would greatly improve situations like i sent above. For example, swiping right and slighly down will already send č, as that is what i intended to do anyway.

### PR DESCRIPTION
**Pull request by penn5**
- Closes #344
- Closes #343 
- Works towards #169
- Implements #234 (using the current keyboard types, and with automatic checking of validity during deserialization)
- Doesn't yet support loading external keyboard layouts (although the logic is there, the UI is not)
- Ugly code present in the settings UI, because I don't have time to convert everything to be better

The commit history contains a tool to convert keyboard layouts from the old format to JSON, the process is simple, just run the app then pull the file.

### CODE REVIEW

**Comment by dessalines** [comment]
Please separate these into feature-specific PRs.

Especially the stuff where you removed every keyboard layout. The checked -> unchecked keyboard layout stuff is something I probably don't want to support.

**Comment by penn5** [comment]
The keyboard layout loading is not unchecked, it is checked when it is loaded.

Anyway if you really want to keep your keyboard layouts present as code rather than json that's possible too, but i don't see any reason to restrict loading them externally as users are obviously responsible for the layouts they load, you have no part in it.

**Comment by penn5** [comment]
Splitting into separate PRs -- yeah, I should. But I don't know if I have time. A lot of the code can be copy-pasted if you want to take only a specific feature. Just please maintain the authorship.

**Comment by dessalines** [comment]
Its a concious decision to keep all the keyboard layouts compile-time checked. As we add / remove more features and abilities to keyboard definitions, I'd like the compiler and CI to be able to catch all of those. I'd also rather not maintain two separate types of keyboard definitions, as mentioned in another issue.

But yes whenever you get the time, extract the other additions here into and I can review / merge.

**Comment by penn5** [comment]
Again, it's the same type of definition. Literally the same type. Maintanence is zero. I can restore the coded definitions. But I maintain you should support custom layouts, a lot of people want it and it's not difficult to implement.

**Comment by nejni-marji** [comment]
> Splitting into separate PRs -- yeah, I should. But I don't know if I have time. A lot of the code can be copy-pasted if you want to take only a specific feature. Just please maintain the authorship.

I'm interested in cleaning up the code for #344, but I'm not sure _how_ to maintain authorship. I don't want to revert file deletion, and I can't cherry-pick commits either because @penn5 put multiple features in one commit. I have separated out the relevant code, but I had to make a new commit for it. I could edit the commit authorship, or I could mark @penn5 as a [co-author](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors), but the choice is up to you and the maintainer.

**Comment by dessalines** [comment]
You can check out this PR, and extract / copy over those specific parts of the code. Authorship stuff I leave up to you.

**Comment by KraXen72** [comment]
is this going to be split up into multiple pull requests? it would be a shame to let this die, since it implements a bunch of cool features. Thanks!

**Comment by nejni-marji** [comment]
I'm taking only the swipe assist feature (#344) and am actually just about to submit a new PR for it. As for custom layouts, I leave that to someone else to sort out.

**Comment by KraXen72** [comment]
okay, thanks. what about #343?

**Comment by nejni-marji** [comment]
With the elimination of SwipeNWay entirely, a high enough setting for swipe assist _should_ make all swipe angles register the nearest of multiple possible swipe inputs. Does that satisfy #343 for you?

**Comment by KraXen72** [comment]
Yes.

**Comment by dessalines** [comment]
IMO #343  should stay, and we should be hard-coding the different key swipe types, rather than removing that info from all the keyboard definitions. The bulk of penn's additions here were "let's remove compile time checking from the code base".

**Pull request closed without merging**
