### PR TITLE
Added Two-Hands layout

### PR DESCRIPTION
**Pull request by Lavin-tom**
I drew inspiration from English version 4 and incorporated a four-column arrangement to create a new layout suitable for a two-handed configuration in Kotlin. However, please note that this untested design may not be the most optimal for a two-hand keyboard layout.

### CODE REVIEW

**Review by dessalines — COMMENTED** [review]
Run `./gradlew formatKotlin` to pass lint

**Comment by dessalines** [comment]
I've also merged some other keyboards, so you'll have to add this one after those.

**Comment by Lavin-tom** [comment]
First time facing an issue with a <b>conflict</b> files, don't know how to rectify the issue

**Review by dessalines — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
