### PR TITLE
Added ENThumbKeyWriter layout

### PR DESCRIPTION
**Pull request by locrianz**
Layout includes smart quotes and apostrophes, ellipsis, and m- and n-dash.

### CODE REVIEW

**Comment by locrianz** [comment]
I'm not sure what I did wrong to make the checks fail. I forked the repository, added my updated keyboard file, and immediately opened the pull request.

**Comment by pxeemo** [comment]
You should run `./gradlew formatKotlin` to pass checks.

**Comment by dessalines** [comment]
Its okay, I'll handle it from here.

**Review by dessalines — APPROVED** [review]
There are some weird differences between the shifted keyboard and the lowercase that don't make sense to me, but you can always fix them later.

**Pull request merged**
