### PR TITLE
Smart Quotes untested

### PR DESCRIPTION
**Pull request by mruncreative**
I'm sure you can get this to work

### CODE REVIEW

**Comment by mruncreative** [comment]
Woah, I managed to build it without installing any software on my computer.
bxTCt1
How do I download the apk to see if it actually works?

**Review by dessalines — COMMENTED** [review]
You'll need to install android studio to test this. Watch a video or read a tutorial if you can't figure out how to do this.

**Comment by mruncreative** [comment]
Come on. Just do it for m this once. I'm never going to use Kotlin afterwards.

**Comment by dessalines** [comment]
Nope, do your own work. And if you keep bugging me to do free labor for you, then I'm going to ban you from this repo.

**Comment by mruncreative** [comment]
**I** did the labor. It's already done. All you need to do is click merge. I'm pretty sure it works.

**Comment by dessalines** [comment]
You want me to merge something you refuse to test yourself?

**Comment by mruncreative** [comment]
How do you know that it doesn't work?

**Pull request closed without merging**
