### PR TITLE
Add EU ES keyboard

### PR DESCRIPTION
**Pull request by zgll2022**
Add EU keyboard with ES symbols (vowel accents and ñ)

### CODE REVIEW

**Review by dessalines — CHANGES_REQUESTED** [review]
Check the other PRs, you also need to add this to KeyboardDefinitions.

**Review by dessalines — COMMENTED** [review]
Run `./gradlew formatKotlin` to pass lint.

**Review by dessalines — APPROVED** [review]
I fixed the issue. Thx for this.

**Comment by zgll2022** [comment]
Thank you very much!

**Pull request merged**
