### PR TITLE
reset multi-tap state after one second delay

### PR DESCRIPTION
**Pull request by iliazeus**
Because I like having multi-tap spacebar enabled, but sometimes do actually want to input multiple spaces.

### CODE REVIEW

**Comment by DiegoLpVn** [comment]
It would be nice to make this time configurable and add it to settings as well

**Comment by dessalines** [comment]
Seems fine, but I won't be back until next week to be able to test it.

**Review by dessalines — COMMENTED** [review]
Question: did you test this? If you did, post a video for it plz.

**Comment by dessalines** [comment]
@DiegoLpVn a sane default seems fine, but if you'd like to add that to make it configurable, PRs are welcome.

**Review by dessalines — APPROVED** [review]
Worked great, thank you!

**Pull request merged**
