### PR TITLE
Add mathematical keyboard layout

### PR DESCRIPTION
**Pull request by Kuna42**
Create a new keyboard layout for typing mathematical symbols.

The Keys are currently not sorted by frequency of use. 
Those are sorted by similarity. ( As much as possible )
I would first try this layout out, so can you please mark it as an experimental layout?

### CODE REVIEW

**Comment by sslater11** [comment]
When I saw this, I thought it was a calculator built into the keyboard and thought that was a great idea haha.

**Review by dessalines — COMMENTED** [review]
Interesting!

This is unused, you need to add it to the keyboard_definitions file too. Check the recent PRs.

And make sure you run `./gradlew formatKotlin` to pass lint.

**Review by dessalines — APPROVED** [review]
Thx!

**Comment by Kuna42** [comment]
I tried to press all keys. But this characters appeared.

thumb_key_MATH-keyboard

@dessalines  what could be wrong?

**Comment by dessalines** [comment]
I don't know what *this character appeared* means, but as you made this keyboard, I can't help you with it.

**Comment by sslater11** [comment]
I saw this and wasn't sure what you meant either :sweat_smile:.
Could you please explain the issue fully?

**Comment by Kuna42** [comment]
Sorry for this bad explanation of my problem.
Later when i have more time left, i try to get a better description of my problem.

**Comment by Kuna42** [comment]
Now, the problem should be fixed.
I didn't read the file correctly.
This [Pull Request](https://github.com/dessalines/thumb-key/pull/594) has know the things i missed the first time.

**Pull request merged**
