### PR TITLE
Use key from the numeric layer if a key is unused in the active layer

### LINKED ISSUE #646: Most special characters are only usable from number pane
**Thumb-Key Version**
2.6.9, from f-droid

**Describe the bug**
Compared to messagease, it's slightly annoying to type special characters.

**To Reproduce**
1. Enable MessagEase, english layout
2. Swipe left from n
3. Note that `+` is entered
4. Enable ThumbKey, english messagease layout
5. Swipe left from n
6. `l` is entered
7. Enable number mode
8. Swipe left from 2 (n)
9. `+` is entered

### PR DESCRIPTION
**Pull request by nightkr**
Fixes #646

### CODE REVIEW

**Comment by dessalines** [comment]
This is more hidden functionality, and it also isn't guaranteed that every layout will use or prefer a numeric layout.

**Comment by nightkr** [comment]
In most layouts, most symbols are only defined in the numeric layer, meaning that accessing them requires you to 1) tap the layer switch button to switch to numeric, 2) type the symbol, 3) tap the layer switch button to revert to the main layer.

With this PR, you'd have immediate access all symbols (unless they shadow a letter), and be able to skip straight to step 2. This also mirrors the behaviour of MessagEase.

The number itself would never be accessible, since all layers define a center action (unless that was a reference to #652 instead).

**Comment by dessalines** [comment]
This seems like it would conflict with the swipe types then, which should automatically pick the letter closest to your swipe, rather than a hidden secret one.

IMO the symbols-focused keyboards (of which there are many), would be a better way to handle this.

**Comment by nightkr** [comment]
> IMO the symbols-focused keyboards (of which there are many), would be a better way to handle this.

Is it viable to maintain a symbols variant of every layout for every language?

**Comment by dessalines** [comment]
A lot of languages will probably have their own specific set of symbols that makes sense. Or certain programmer layouts might want specific symbols on their unshifted layers.

Its better to handle customization at the keyboard-specific level, so that individual users of those keyboards can have it be exactly what they need. As opposed to trying to add functionality to every keyboard where it doesn't always make sense.

**Comment by Mizar01** [comment]
Hello there. I have the same problem. I'm used to the italian  layout on messagease, with a lot of duplicated symbols on both letter and numeric layout. On Thumbkey i set the same layout, but most of the punctuation symbols are found only switching to numeric pad.

For example the italian layout for letters is full of empty spaces. I would to use at least the '?' and '!' symbols. There some kind of customization we can set somewhere? It would be nice to be able to save a custom layout.

**Comment by dessalines** [comment]
I'm not creating an in-app editor (you can see the 10+ closed issues on why) but you can add an italian symbols layout if you like. Follow the instructions in the README.

**Comment by Mizar01** [comment]
Thank you. I'll look into it.

Nevertheless, I would suggest to edit, if possible, the current italian message ease layout, because in the current state, it can be filled with the punctuation symbols, at least those more useful (5 or less i think). Adding another layout from the app itself could be useful only for personal use, but I would not add on the already very long list of layouts you can choose.

Most used (not present at the moment in the letter layout) @  ?  !  " (  ) & +

**Comment by dessalines** [comment]
Its totally fine to add a keyboard that only you use, I'm sure a lot of our keyboards are like that.

There seems to be a standard of having a simple keyboard, then a symbols variant one. Esp since people want the messagease and thumb-key layouts to be simple. 

Totally fine to create a symbols variant for italian messagease also.

**Pull request closed without merging**
