### PR TITLE
Adding slovak layout. Fixes #487

### LINKED ISSUE #487: Slovak layout 🇸🇰
After a long time I have finally finished making the SK layout, also after some help from the existing Czech one. Thank you for this great keyboard, I am proud to be hopefully helpful in its way to the hands of more people!  
[The .kt keyboard file](https://github.com/Marek-maker/thumb-key/blob/main/app/src/main/java/com/dessalines/thumbkey/keyboards/ThumbKeySKv1.kt)

### PR DESCRIPTION
**Pull request by dessalines**

### CODE REVIEW

**Comment by KraXen72** [comment]
this slovak layout has same default letters as the en v4. can it be considered a true slovak layout then? my layout (en + sk multi) is labeled as a derivative of the english layout.

**Comment by KraXen72** [comment]
same thing with the czech layout - it's just a derivative of the en v4 layout. not saying that's a bad thing, but i think it shoudl be labeled as such.

**Comment by dessalines** [comment]
100% agree with that.

If you want to fix those keyboards tho, I'd be glad to merge changes.

**Comment by KraXen72** [comment]
i fixed it for the czech keyboard, but there are now 2 env4 deriative slovak layouts (mine and this one). How do i differentiate them? I don't want to use v1 and v2, because v2 implies it is better than v1, while neither of the layouts is necessarily better, only different.

**Comment by dessalines** [comment]
You can replace the existing one, since its actually an anglo-centric one. Whoever made that can do a multi-language keyboard like the other ones if they prefere.

**Comment by KraXen72** [comment]
> You can replace the existing one
  
implying the new "slovak" one (`SKThumbKey.kt`), which is an incorrectly named ENv4 derivative, or the EN+SK multil layout (`ENThumbKeyMulti.kt`)? if you mean the latter, i am not going to replace that, since i contributed that and i use it. it also follows proper naming of it being a ENv4 derivative.

I don't have a problem with keeping both, but let's rename them. That was my question, how to properly differentiate them. I can call mine. I am thinking about appending author name at the end, but that would get long pretty quickly. However, i don't have a better solution currently.

 I was asking if you have any ideas on the naming. Thanks!

**Comment by dessalines** [comment]
Check the naming on the multi-language keyboards, usually its ENEO or something like that.

**Comment by KraXen72** [comment]
yes, but these are essentially 2 variations of the same keyboard, `EN Thumb-key english (EN+SK multi)` (according to how other multi-layouts are named).
The newly merged version is only slighly different from the already existing layout. @Marek-maker, did you add the keyboard, because you didn't find my layout, or did you want your own? if you wanted your own, then I think we should keep both.

**Comment by Marek-maker** [comment]
Oh, if I understand this disscusion correctly @KraXen72 already made an EN+SK multi layout. I did not know about it, my bad that I have not checked for it. Iam completely fine with keeping only yours as you have the proper naming. To avoid future misunderstandements do you have any info if there is someone working on a pure slovak layout so that there is no work duplicity?  This was my first contribution to an opensource project and I wasnt used to the practices of contribution yet.

**Comment by KraXen72** [comment]
@Marek-maker there is some initial work done by dj sushi in #151, but i don't think they finished it.

if you want to, you can make a pr that removes/renames your layout, or i could do it when i get to it later.

also, no worries - even the fact that you're contributing to open source is awesome, and i'm sorry you accidentally did duplicate work (you could still just rename if you want to keep it instead of removing)

**Pull request merged**
