### PR TITLE
Fixed layouts indexes in Types.kt

### PR DESCRIPTION
**Pull request by Chirikumbrah**
Now all layouts should be displayed correctly :)

### CODE REVIEW

**Review by roihershberg — CHANGES_REQUESTED** [review]
Hi! While working on a Hebrew layout I noticed that the only change you need to make in this file is changing the index of the `ThumbKeyFIv1Wide` layout to 22. This is due to this commit which adds the layout but not assigns a new index: https://github.com/dessalines/thumb-key/commit/2e76ba4686be660dfe351099599f38b62b5a4ac9

**Comment by Chirikumbrah** [comment]
@roihershberg, the problem was in the 18th index (suomi wide & ru with symbols were the same), so I added +1 to every layout created by me)

**Comment by Chirikumbrah** [comment]
@roihershberg, yeah, now I see. I've  looked at the changes and u're right)
I'll leave it as is for now, but anyway, thank you for your suggestion)

**Comment by roihershberg** [comment]
I think that the problem when messing with the indexes is that it will change the chosen layouts in the settings. I haven't looked at the code but I'm almost certain that the chosen layouts are stored in the shared preferences by their index. That's how I discovered this bug.
So every layout that the index have been changed for in this PR and a user selected them as the layouts he wants to use, will now be a different layout and the user may suddenly see a completely different language and will not understand what happened.
Therefore, a change in the indexes should be as minimal as possible.

Try a version of this app before your changes, choose the layouts that you've changed the index for and then install the version of the app with your changes and see if you now have different layouts or a different order of the layouts.

**Comment by Chirikumbrah** [comment]
> Try a version of this app before your changes, choose the layouts that you've changed the index for and then install the version of the app with your changes and see if you now have different layouts or a different order of the layouts.

I did that)
As I said before the problem was here)


Now it's ok and I'm using version built with files from this PR)

**Review by dessalines — APPROVED** [review]

**Comment by roihershberg** [comment]
@Chirikumbrah @dessalines 
Yeah this is the problem but only `ThumbKeyFIv1Wide` should be changed to `22`.
This should be reverted. The problem that I was suspecting is correct. The chosen layouts of the users will be changed.
Look at the video demonstrating how the layouts are changing after the patch:

https://github.com/dessalines/thumb-key/assets/22105369/af2004b6-45c6-401f-b1e9-6533b1d7576c

**Comment by dessalines** [comment]
Could you do a PR to fix this?

**Comment by roihershberg** [comment]
Yes

**Comment by dessalines** [comment]
No layouts should have changed indices as of the 1.0.0

**Pull request merged**
